- name: Install dependencies
  ansible.builtin.apt:
    pkg: python3-certbot-dns-cloudflare

- name: Configure certbot
  ansible.builtin.template:
    src: cloudflare.ini.j2
    dest: "/etc/letsencrypt/cloudflare.ini"
    mode: '0640'

- name: Run command
  ansible.builtin.command:
    cmd: "certbot certonly --agree-tos -n -m {{ certbot_cloudflare_email }} --dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini -d {{ certbot_domain }} -d *.{{ certbot_domain }}"
    creates: "/etc/letsencrypt/live/certbot_domain/fullchain.pem"
  with_items: "{{ certbot_domain }}"
  loop_control:
    loop_var: certbot_domain
