- name: Install certbot and plugin
  ansible.builtin.include_tasks: "{{ certbot_type }}.yml"

- name: Set permission to path
  ansible.builtin.file:
    path: "/etc/letsencrypt/{{ item }}"
    mode: 'g+r'
    group: www-data
    recurse: true
  with_items:
    - archive
    - live

- name: Cron - add certbot renew
  ansible.builtin.cron:
    name: certbot renew
    hour: '01'
    minute: '23'
    job: certbot renew
  when: certbot is defined
